name: Build and deploy ASP.NET MVC app to Azure Web App - managementgym

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore ./GYMMANAGEMENT.sln

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Build with MSBuild
        run: msbuild ./GYMMANAGEMENT.sln /p:Configuration=Release

      - name: Publish to folder
        run: msbuild ./GYMMANAGEMENT/GYMMANAGEMENT.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:PublishUrl=./publish_output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./publish_output

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ./publish_output

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC8EA3FDAA664AA4A7FAAFEA3B5BBB9E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0194D3BF9ED4C8199F14890DEE22889 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D71B1AAF1356446CBEA13991B5E86FC4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'managementgym' # Tên App Service trong Azure Portal
          slot-name: 'Production'
          package: ./publish_output

